# Configure system attributes on Nexus switch
# Tested on nxosv 9000
#

---

- name: Adding system attributes to switch
  hosts: nxos
  connection: local
  gather_facts: no
  
  vars:
    provider:
	  username: admin
	  password: password
	  transport: nxapi
	  host: "{{ inventory_hostname }}"

  tasks:
  
  - name: ensure hostname is configured
    nxos_system:
      hostname: "{{ inventory_hostname }}"
  	  state: present
  	  provider: "{{ provider }}"
  	
  - name: ensure domain-name is configured
    nxos_system:
      domain_name: home.local	
  	  state: present
  	  provider: "{{ provider }}"
  	
