# Configure SNMP on Nexus switch
# Tested on nxosv 9000
#


---

- name: Adding SNMP configuration on Nexus switch
  hosts: nxos
  connection: local
  gather_facts: no
  
  vars:
    provider:
	  username: admin
	  password: password
	  transport: nxapi
	  host: "{{ inventory_hostname }}"

  task:
  
  - name: ensure v2c community string is configured
    nxos_snmp_community:
      community: mycommunity
  	  access: ro
  	  state: present
  	  provider: "{{ provider }}"
  	
  - name: ensure snmp contact is configured
    contact: myemail@home.local
  	  state: present
  	  provider: "{{ provider }}"
  	
  - name: ensure snmp location is configured
    nxos_snmp_location:
	  location: mylocation
	  state: present
  	  provider: "{{ provider }}"
  	
  - name: ensure snmp v3 user is configured
    nxos_snmp_user: 
      user: snmpuser
	  authentication: sha
	  encrypt: true
	  group: network-operator
	  pwd: password
	  privacy: password
	  state: present
  	  provider: "{{ provider }}"
  	
  - name: ensure v2c snmp host is configured
    nxos_snmp_host: 
      community: mycommunity
  	  snmp_host: 10.1.1.1
  	  snmp_trap: trap
  	  src_intf: mgmt0
	  version: v2c
	  vrf: management
	  state: present
  	  provider: "{{ provider }}"
  	
 